package sqlx

import "testing"

func TestConvert(t *testing.T) {
	Convert("-- generated by converter, github: https://github.com/kesonan/converter\n\nCREATE TABLE IF NOT EXISTS `table_name` (\n  `id` int unsigned NOT NULL AUTO_INCREMENT,\n  `active` int(11) NOT NULL DEFAULT 0,\n  `create_time` int(11) NOT NULL DEFAULT 0,\n  `current_date` date NOT NULL DEFAULT '1970-01-01',\n  `current_time` time NOT NULL DEFAULT '00:00:01',\n  `description` varchar(255) NOT NULL DEFAULT '',\n  `github` varchar(255) NOT NULL DEFAULT '',\n  `join_year` varchar(255) NOT NULL DEFAULT '',\n  `name` varchar(255) NOT NULL DEFAULT '',\n  `stars` decimal NOT NULL DEFAULT 0.00,\n  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8;", "")
}
