package constx

const (
	MayIdColumn     = "id"
	TimeStampEnd    = 2147454847
	Indent          = "  "
	HeaderText      = "generated by converter, github: https://github.com/kesonan/converter"
	ProtobufTypeAny = "\nimport \"google/protobuf/any.proto\";\n"
	GoctlAPIService = `service API {
    @handler api
    post /to/your/path (GeneratedRequest) returns (GeneratedResponse)
}`
)

const (
	TypeJSON     = "JSON"
	TypeSQL      = "SQL"
	TypeTOML     = "TOML"
	TypeYAML     = "YAML"
	TypeProtoBuf = "PROTOBUF"
	TypeGoctlAPI = "GOCTL API"
	TypeGoStruct = "GO STRUCT"
	TypeXml      = "XML"
)
